<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class lov_medicalprocedures extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	Model::unguard();

        DB::statement("
	    	INSERT INTO lov_medicalprocedures(procedure_code,procedure_description) VALUES
	    	('10060', 'Incision and drainage of abscess (e.g., carbuncle, suppurative hidradenitis, cutaneous or subcutaneous abscess, cyst, furuncle, or paronychia)'), 
			('10080', 'Incision and drainage of pilonidal cyst'), 
			('10120', 'Incision and removal of foreign body, subcutaneous tissues'), 
			('10140', 'Incision and drainage of hematoma, seroma, or fluid collection'), 
			('10160', 'Puncture aspiration of abscess, hematoma, bulla, or cyst'), 
			('10180', 'Incision and drainage, complex, postoperative wound infection'), 
			('11000', 'Debridement of extensive eczematous or infected skin'), 
			('11010', 'Debridement including removal of foreign material associated w/ open fracture(s) and/or dislocation(s); skin and subcutaneous tissues'), 
			('11011', 'Debridement including removal of foreign material associated w/ open fracture(s) and/or dislocation(s); skin, subcutaneous tissue, muscle fascia, and muscle'), 
			('11012', 'Debridement including removal of foreign material associated w/ open fracture(s) and/or dislocation(s); skin, subcutaneous tissue, muscle fascia, muscle, and bone'), 
			('11040', 'Debridement; skin, partial thickness'), 
			('11041', 'Debridement; skin, full thickness'), 
			('11042', 'Debridement; skin, and subcutaneous tissue'), 
			('11043', 'Debridement; skin, subcutaneous tissue, and muscle'), 
			('11044', 'Debridement; skin, subcutaneous tissue, muscle, and bone'), 
			('11050', 'Paring or curettement of benign hyperkeratotic skin lesion w/ or w/o chemical cauterization (such as verrucae or clavi) not extending through the stratum corneum (e.g., callus or wart) w/ or w/o local anesthesia; single lesion'), 
			('11051', 'Paring or curettement of benign hyperkeratotic skin lesion w/ or w/o chemical cauterization (such as verrucae or clavi) not extending through the stratum corneum (e.g., callus or wart) w/ or w/o local anesthesia; two to four lesions'), 
			('11052', 'Paring or curettement of benign hyperkeratotic skin lesion w/ or w/o chemical cauterization (such as verrucae or clavi) not extending through the stratum corneum (e.g., callus or wart) w/ or w/o local anesthesia; more than four lesions'), 
			('11100', 'Biopsy of skin, subcutaneous tissue and/or mucous membrane (including simple closure), unless otherwise listed; single or multiple lesion'), 
			('11300', 'Shaving of epidermal or dermal lesion, single lesion, trunk, arms or legs; lesion diameter 0.5 cm or less'), 
			('11301', 'Shaving of epidermal or dermal lesion, single lesion, trunk, arms or legs; lesion diameter 0.6 to 1.0 cm'), 
			('11302', 'Shaving of epidermal or dermal lesion, single lesion, trunk, arms or legs; lesion diameter 1.1 to 2.0 cm'), 
			('11303', 'Shaving of epidermal or dermal lesion, single lesion, trunk, arms or legs; lesion diameter over 2.0 cm'), 
			('11305', 'Shaving of epidermal or dermal lesion, single lesion, scalp, neck, hands, feet, genitalia; lesion diameter 0.5 cm or less'), 
			('11306', 'Shaving of epidermal or dermal lesion, single lesion, scalp, neck, hands, feet, genitalia; lesion diameter 0.6 to 1.0 cm'), 
			('11307', 'Shaving of epidermal or dermal lesion, single lesion, scalp, neck, hands, feet, genitalia; lesion diameter 1.1 to 2.0 cm'), 
			('11308', 'Shaving of epidermal or dermal lesion, single lesion, scalp, neck, hands, feet, genitalia; lesion diameter over 2.0 cm'), 
			('11310', 'Shaving of epidermal or dermal lesion, single lesion, face, ears, eyelids, nose ,lips, mucous membrane; lesion diameter 0.5 cm or less'), 
			('11311', 'Shaving of epidermal or dermal lesion, single lesion, face, ears, eyelids, nose ,lips, mucous membrane; lesion diameter 0.6 to 1.0 cm'), 
			('11312', 'Shaving of epidermal or dermal lesion, single lesion, face, ears, eyelids, nose ,lips, mucous membrane; lesion diameter 1.1 to 2.0 cm'), 
			('11313', 'Shaving of epidermal or dermal lesion, single lesion, face, ears, eyelids, nose ,lips, mucous membrane; lesion diameter over 2.0 cm'), 
			('11400', 'Excision, benign lesion, except skin tag (unless listed elsewhere), trunk, arms or legs; lesion diameter 0.5 cm or less'), 
			('11401', 'Excision, benign lesion, except skin tag (unless listed elsewhere), trunk, arms or legs; lesion diameter 0.6 to 1.0 cm'), 
			('11402', 'Excision, benign lesion, except skin tag (unless listed elsewhere), trunk, arms or legs; lesion diameter 1.1 to 2.0 cm'), 
			('11403', 'Excision, benign lesion, except skin tag (unless listed elsewhere), trunk, arms or legs; lesion diameter 2.1 to 3.0 cm'), 
			('11404', 'Excision, benign lesion, except skin tag (unless listed elsewhere), trunk, arms or legs; lesion diameter 3.1 to 4.0 cm'), 
			('11406', 'Excision, benign lesion, except skin tag (unless listed elsewhere), trunk, arms or legs; lesion diameter over 4.0 cm'), 
			('11420', 'Excision, benign lesion, except skin tag (unless listed elsewhere), scalp, neck, hands, feet, genitalia; lesion diameter 0.5 cm or less'), 
			('11421', 'Excision, benign lesion, except skin tag (unless listed elsewhere), scalp, neck, hands, feet, genitalia; lesion diameter 0.6 to 1.0 cm'), 
			('11422', 'Excision, benign lesion, except skin tag (unless listed elsewhere), scalp, neck, hands, feet, genitalia; lesion diameter 1.1 to 2.0 cm'), 
			('11423', 'Excision, benign lesion, except skin tag (unless listed elsewhere), scalp, neck, hands, feet, genitalia; lesion diameter 2.1 to 3.0 cm'), 
			('11424', 'Excision, benign lesion, except skin tag (unless listed elsewhere), scalp, neck, hands, feet, genitalia; lesion diameter 3.1 to 4.0 cm'), 
			('11426', 'Excision, benign lesion, except skin tag (unless listed elsewhere), scalp, neck, hands, feet, genitalia; lesion diameter over 4.0 cm'), 
			('11440', 'Excision, other benign lesion (unless listed elsewhere), face, ears, eyelids, nose, lips, mucous membrane; lesion diameter 0.5 cm or less'), 
			('11441', 'Excision, other benign lesion (unless listed elsewhere), face, ears, eyelids, nose, lips, mucous membrane; lesion diameter 0.6 to 1.0 cm'), 
			('11442', 'Excision, other benign lesion (unless listed elsewhere), face, ears, eyelids, nose, lips, mucous membrane; lesion diameter 1.1 to 2.0 cm'), 
			('11443', 'Excision, other benign lesion (unless listed elsewhere), face, ears, eyelids, nose, lips, mucous membrane; lesion diameter 2.1 to 3.0 cm'), 
			('11444', 'Excision, other benign lesion (unless listed elsewhere), face, ears, eyelids, nose, lips, mucous membrane; lesion diameter 3.1 to 4.0 cm'), 
			('11446', 'Excision, other benign lesion (unless listed elsewhere), face, ears, eyelids, nose, lips, mucous membrane; lesion diameter over 4.0 cm'), 
			('11450', 'Excision of skin and subcutaneous tissue for hidradenitis, axillary'), 
			('11462', 'Excision of skin and subcutaneous tissue for hidradenitis, inguinal'), 
			('11470', 'Excision of skin and subcutaneous tissue for hidradenitis, perianal, perineal or umbilical'), 
			('11600', 'Excision, malignant lesion, trunk, arms, or legs; lesion diameter 0.5 cm or less'), 
			('11601', 'Excision, malignant lesion, trunk, arms, or legs; lesion diameter 0.6 to 1.0 cm'), 
			('11602', 'Excision, malignant lesion, trunk, arms, or legs; lesion diameter 1.1 to 2.0 cm'), 
			('11603', 'Excision, malignant lesion, trunk, arms, or legs; lesion diameter 2.1 to 3.0 cm'), 
			('11604', 'Excision, malignant lesion, trunk, arms, or legs; lesion diameter 3.1 to 4.0 cm'), 
			('11606', 'Excision, malignant lesion, trunk, arms, or legs; lesion diameter over 4.0 cm'), 
			('11620', 'Excision, malignant lesion, scalp, neck, hands, feet, genitalia; lesion diameter 0.5 cm or less'), 
			('11621', 'Excision, malignant lesion, scalp, neck, hands, feet, genitalia; lesion diameter 0.6 to 1.0 cm'), 
			('11622', 'Excision, malignant lesion, scalp, neck, hands, feet, genitalia; lesion diameter 1.1 to 2.0 cm'), 
			('11623', 'Excision, malignant lesion, scalp, neck, hands, feet, genitalia; lesion diameter 2.1 to 3.0 cm'), 
			('11624', 'Excision, malignant lesion, scalp, neck, hands, feet, genitalia; lesion diameter 3.1 to 4.0 cm'), 
			('11626', 'Excision, malignant lesion, scalp, neck, hands, feet, genitalia; lesion diameter over 4.0 cm'), 
			('11640', 'Excision, malignant lesion, face, ears, eyelids, nose, lips; lesion diameter 0.5 cm or less'), 
			('11641', 'Excision, malignant lesion, face, ears, eyelids, nose, lips; lesion diameter 0.6 to 1.0 cm'), 
			('11642', 'Excision, malignant lesion, face, ears, eyelids, nose, lips; lesion diameter 1.1 to 2.0 cm'), 
			('11643', 'Excision, malignant lesion, face, ears, eyelids, nose, lips; lesion diameter 2.1 to 3.0 cm'), 
			('11644', 'Excision, malignant lesion, face, ears, eyelids, nose, lips; lesion diameter 3.1 to 4.0 cm'), 
			('11646', 'Excision, malignant lesion, face, ears, eyelids, nose, lips; lesion diameter over 4.0 cm'), 
			('11720', 'Debridement of nail(s) by any method(s); one to five'), 
			('11721', 'Debridement of nail(s) by any method(s); six or more'), 
			('11730', 'Avulsion of nail plate, partial or complete'), 
			('11740', 'Evacuation of subungual hematoma'), 
			('11750', 'Excision of nail and nail matrix, partial or complete (e.g., ingrown or deformed nail) for permanent removal'), 
			('11752', 'Excision of nail and nail matrix, partial or complete (e.g., ingrown or deformed nail) for permanent removal w/ amputation of tuft of distal phalanx'), 
			('11755', 'Biopsy of nail unit, any method (e.g., plate, bed, matrix, hyponychium, proximal and lateral nail folds)'), 
			('11760', 'Repair of nail bed'), 
			('11762', 'Reconstruction of nail bed w/ graft'), 
			('11765', 'Wedge excision of skin of nail fold (e.g., for ingrown toenail)'), 
			('11770', 'Excision of pilonidal cyst or sinus'), 
			('12001', 'Simple repair of superficial wounds of scalp, neck, axillae, external genitalia, trunk and/or extremities (including hands and feet); 2.5 cm or less'), 
			('12002', 'Simple repair of superficial wounds of scalp, neck, axillae, external genitalia, trunk and/or extremities (including hands and feet); 2.6 cm to 7.5 cm'), 
			('12004', 'Simple repair of superficial wounds of scalp, neck, axillae, external genitalia, trunk and/or extremities (including hands and feet); 7.6 cm to 12.5 cm'), 
			('12005', 'Simple repair of superficial wounds of scalp, neck, axillae, external genitalia, trunk and/or extremities (including hands and feet); 12.6 cm to 20.0 cm'), 
			('12006', 'Simple repair of superficial wounds of scalp, neck, axillae, external genitalia, trunk and/or extremities (including hands and feet); 20.1 cm to 30.0 cm'), 
			('12007', 'Simple repair of superficial wounds of scalp, neck, axillae, external genitalia, trunk and/or extremities (including hands and feet); over 30.0 cm'), 
			('12011', 'Simple repair of superficial wounds of face, ears, eyelids, nose, lips and/or mucous membranes; 2.5 cm or less'), 
			('12013', 'Simple repair of superficial wounds of face, ears, eyelids, nose, lips and/or mucous membranes; 2.6 cm to 5.0 cm'), 
			('12014', 'Simple repair of superficial wounds of face, ears, eyelids, nose, lips and/or mucous membranes; 5.1 cm to 7.5 cm'), 
			('12015', 'Simple repair of superficial wounds of face, ears, eyelids, nose, lips and/or mucous membranes; 7.6 cm to 12.5 cm'), 
			('12016', 'Simple repair of superficial wounds of face, ears, eyelids, nose, lips and/or mucous membranes; 12.6 cm to 20.0 cm'), 
			('12017', 'Simple repair of superficial wounds of face, ears, eyelids, nose, lips and/or mucous membranes; 20.1 cm to 30.0 cm'), 
			('12018', 'Simple repair of superficial wounds of face, ears, eyelids, nose, lips and/or mucous membranes; over 30.0 cm'), 
			('12031', 'Layer closure of wounds of scalp, axillae, trunk, and/or extremities (excluding hands and feet); 2.5 cm or less'), 
			('12032', 'Layer closure of wounds of scalp, axillae, trunk, and/or extremities (excluding hands and feet); 2.6 cm to 7.5 cm'), 
			('12034', 'Layer closure of wounds of scalp, axillae, trunk, and/or extremities (excluding hands and feet); 7.6 cm to 12.5 cm'), 
			('12035', 'Layer closure of wounds of scalp, axillae, trunk, and/or extremities (excluding hands and feet); 12.6 cm to 20.0 cm'), 
			('12036', 'Layer closure of wounds of scalp, axillae, trunk, and/or extremities (excluding hands and feet); 20.1 cm to 30.0 cm'), 
			('12037', 'Layer closure of wounds of scalp, axillae, trunk, and/or extremities (excluding hands and feet); over 30.0 cm'), 
			('12041', 'Layer closure of wounds of neck, hands, feet and/or external genitalia; 2.5 cm or less'), 
			('12042', 'Layer closure of wounds of neck, hands, feet and/or external genitalia; 2.6 cm to 7.5 cm'), 
			('12044', 'Layer closure of wounds of neck, hands, feet and/or external genitalia; 7.6 cm to 12.5 cm'), 
			('12045', 'Layer closure of wounds of neck, hands, feet and/or external genitalia; 12.6 cm to 20.0 cm'), 
			('12046', 'Layer closure of wounds of neck, hands, feet and/or external genitalia; 20.1 cm to 30.0 cm'), 
			('12047', 'Layer closure of wounds of neck, hands, feet and/or external genitalia; over 30.0 cm'), 
			('12051', 'Layer closure of wounds of face, ears, eyelids, nose, lips and/or mucous membrances; 2.5 cm or less'), 
			('12052', 'Layer closure of wounds of face, ears, eyelids, nose, lips and/or mucous membrances; 2.6 cm to 5.0 cm'), 
			('12053', 'Layer closure of wounds of face, ears, eyelids, nose, lips and/or mucous membrances; 5.1 cm to 7.5 cm'), 
			('12054', 'Layer closure of wounds of face, ears, eyelids, nose, lips and/or mucous membrances; 7.6 cm to 12.5 cm'), 
			('12055', 'Layer closure of wounds of face, ears, eyelids, nose, lips and/or mucous membrances; 12.6 cm to 20.0 cm'), 
			('12056', 'Layer closure of wounds of face, ears, eyelids, nose, lips and/or mucous membrances; 20.1 cm to 30.0 cm'), 
			('12057', 'Layer closure of wounds of face, ears, eyelids, nose, lips and/or mucous membrances; over 30.0 cm'), 
			('14000', 'Adjacent tissue transfer or rearrangement, trunk; defect 10 sq cm or less'), 
			('14001', 'Adjacent tissue transfer or rearrangement, trunk; defect 10.1 sq cm to 30.0 sq cm'), 
			('14020', 'Adjacent tissue transfer or rearrangement, scalp, arms and/or legs; defect 10 sq cm or less'), 
			('14021', 'Adjacent tissue transfer or rearrangement, scalp, arms and/or legs; defect 10.1 sq cm to 30.0 sq cm'), 
			('14040', 'Adjacent tissue transfer or rearrangement, forehead, cheeks, chin, mouth, neck, axillae, genitalia, hands and/or feet; defect 10 sq cm or less'), 
			('14041', 'Adjacent tissue transfer or rearrangement, forehead, cheeks, chin, mouth, neck, axillae, genitalia, hands and/or feet; defect 10.1 sq cm to 30.0 sq cm'), 
			('14060', 'Adjacent tissue transfer or rearrangement, eyelids, nose, ears and/or lips; defect 10 sq cm or less'), 
			('14061', 'Adjacent tissue transfer or rearrangement, eyelids, nose, ears and/or lips; defect 10.1 sq cm to 30.0 sq cm'), 
			('14300', 'Adjacent tissue transfer or rearrangement, more than 30 sq cm, unusual or complicated, any area'), 
			('14350', 'Filleted finger or toe flap, including preparation of recipient site'), 
			('15050', 'Pinch graft, single or multiple, to cover small ulcer, tip or digit, or other minimal open area (except on face), up to defect size 2 cm diameter'), 
			('15100', 'Split graft, trunk, scalp, arms, legs, hands, and/or feet (except multiple digits); 100 sq cm or less, or each one percent of body area of infants and children (except 15050)'), 
			('15120', 'Split graft, face, eyelids, mouth, neck, ears, orbits, genitalia, and/or multiple digits; 100 sq cm or less, or each one percent of body area of infants and children (except 15050)'), 
			('15200', 'Full thickness graft, free, including direct closure of donor site, trunk; 20 sq cm or less'), 
			('15220', 'Full thickness graft, free, including direct closure of donor site, scalp, arms, and/or legs; 20 sq cm or less'), 
			('15240', 'Full thickness graft, free, including direct closure of donor site, forehead, cheeks, chin, mouth, neck, axillae, genitalia, hands, and/or feet; 20 sq cm or less'), 
			('15260', 'Full thickness graft, free, including direct closure of donor site, nose, ears, eyelids, and/or lips; 20 sq cm or less'), 
			('15350', 'Application of allograft, skin'), 
			('15400', 'Application of xenograft, skin'), 
			('15570', 'Formation of direct or tubed pedicle, w/ or w/o transfer; trunk'), 
			('15572', 'Formation of direct or tubed pedicle, w/ or w/o transfer; scalp, arms, or legs'), 
			('15574', 'Formation of direct or tubed pedicle, w/ or w/o transfer; forehead, cheeks, chin, mouth, neck, axillae, genitalia, hands or feet'), 
			('15576', 'Formation of direct or tubed pedicle, w/ or w/o transfer; eyelids, nose, ears, lips or intraoral'), 
			('15580', 'Cross finger flap, including free graft to donor site'), 
			('15650', 'Transfer, intermediate, of any pedicle flap (e.g., abdomen to wrist, Walking tube), any location'), 
			('15732', 'Muscle, myocutaneous, or fasciocutaneous flap; head and neck (e.g., temporalis, masseter, sternocleidomastoid, levator scapulae)'), 
			('15734', 'Muscle, myocutaneous, or fasciocutaneous flap; trunk'), 
			('15736', 'Muscle, myocutaneous, or fasciocutaneous flap; upper extremity'), 
			('15738', 'Muscle, myocutaneous, or fasciocutaneous flap; lower extremity'), 
			('15740', 'Flap; island pedicle'), 
			('15750', 'Flap; neurovascular pedicle'), 
			('15756', 'Free muscle flap w/ or w/o skin graft w/ microvascular anastomosis'), 
			('15757', 'Free skin flap w/ microvascular anastomosis'), 
			('15758', 'Free fascial flap w/ microvascular anastomosis'), 
			('15760', 'Graft; composite (e.g., full thickness of external ear or nasal ala), including primary closure, donor area'), 
			('15770', 'Graft; derma-fat-fascia'), 
			('15820', 'Blepharoplasty, lower eyelid'), 
			('15822', 'Blepharoplasty, upper eyelid;'), 
			('15823', 'Blepharoplasty, upper eyelid; with excessive skin weighting down lid'), 
			('15840', 'Graft for facial nerve paralysis; free fascia graft (including obtaining fascia)'), 
			('15841', 'Graft for facial nerve paralysis; free muscle graft (including obtaining graft)'), 
			('15842', 'Graft for facial nerve paralysis; free muscle graft by microsurgical technique'), 
			('15845', 'Graft for facial nerve paralysis; regional muscle transfer'), 
			('15920', 'Excision, coccygeal pressure ulcer, w/ coccygectomy; w/ primary suture'), 
			('15922', 'Excision, coccygeal pressure ulcer, w/ coccygectomy; w/ flap closure'), 
			('15931', 'Excision, sacral pressure ulcer, w/ primary suture;'), 
			('15933', 'Excision, sacral pressure ulcer, w/ primary suture; w/ ostectomy'), 
			('15934', 'Excision, sacral pressure ulcer, w/ skin flap closure;'), 
			('15935', 'Excision, sacral pressure ulcer, w/ skin flap closure; w/ ostectomy'), 
			('15936', 'Excision, sacral pressure ulcer, w/ muscle or myocutaneous flap closure;'), 
			('15937', 'Excision, sacral pressure ulcer, w/ muscle or myocutaneous flap closure; w/ ostectomy'), 
			('15940', 'Excision, ischial pressure ulcer, w/ primary suture;'), 
			('15941', 'Excision, ischial pressure ulcer, w/ primary suture; w/ ostectomy (ischiectomy)'), 
			('15944', 'Excision, ischial pressure ulcer, w/ skin flap closure;'), 
			('15945', 'Excision, ischial pressure ulcer, w/ skin flap closure; w/ ostectomy'), 
			('15946', 'Excision, ischial pressure ulcer, w/ ostectomy, w/ muscle or myocutaneous flap closure'), 
			('15950', 'Excision, trochanteric pressure ulcer, w/ primary suture;'), 
			('15951', 'Excision, trochanteric pressure ulcer, w/ primary suture; w/ ostectomy'), 
			('15952', 'Excision, trochanteric pressure ulcer, w/ skin flap closure;'), 
			('15953', 'Excision, trochanteric pressure ulcer, w/ skin flap closure; w/ ostectomy'), 
			('15956', 'Excision, trochanteric pressure ulcer, w/ muscle or myocutaneous flap closure;'), 
			('15958', 'Excision, trochanteric pressure ulcer, w/ muscle or myocutaneous flap closure; w/ ostectomy'), 
			('16010', 'Dressings and/or debridement, initial or subsequent'), 
			('16035', 'Escharotomy'), 
			('16040', 'Excision burn wound, w/o skin grafting, employing alloplastic dressing (e.g., synthetic mesh), any anatomic site'), 
			('17000', 'Destruction by any method, including laser, w/ or w/o surgical curettement, all benign facial lesions or premalignant lesions in any location, or benign lesions other than cutaneous vascular proliferative lesions, including local anesthesia; any number of'), 
			('17100', 'Destruction by any method, including laser, of benign skin lesions other than cutaneous vascular proliferative lesions on any area other than the face, including local anesthesia; any number of lesions'), 
			('17106', 'Destruction of cutaneous vascular proliferative lesions (e.g., laser technique)'), 
			('17110', 'Destruction by any method of flat warts or molluscum contagiosum, milia, all lesions'), 
			('17200', 'Electosurgical destruction of multiple fibrocutaneous tags; all lesions'), 
			('17250', 'Chemical cauterization of granulation tissue (proud flesh, sinus or fistula)'), 
			('17260', 'Destruction, malignant lesion, any method, trunk, arms or legs; lesion diameter 0.5 cm or less'), 
			('17261', 'Destruction, malignant lesion, any method, trunk, arms or legs; lesion diameter 0.6 to 1.0 cm'), 
			('17262', 'Destruction, malignant lesion, any method, trunk, arms or legs; lesion diameter 1.1 to 2.0 cm'), 
			('17263', 'Destruction, malignant lesion, any method, trunk, arms or legs; lesion diameter 2.1 to 3.0 cm'), 
			('17264', 'Destruction, malignant lesion, any method, trunk, arms or legs; lesion diameter 3.1 to 4.0 cm'), 
			('17266', 'Destruction, malignant lesion, any method, trunk, arms or legs; lesion diameter over 4.0 cm'), 
			('17270', 'Destruction, malignant lesion, any method, scalp, neck, hands, feet, genitalia; lesion diameter 0.5 cm or less'), 
			('17271', 'Destruction, malignant lesion, any method, scalp, neck, hands, feet, genitalia; lesion diameter 0.6 to 1.0 cm'), 
			('17272', 'Destruction, malignant lesion, any method, scalp, neck, hands, feet, genitalia; lesion diameter 1.1 to 2.0 cm'), 
			('17273', 'Destruction, malignant lesion, any method, scalp, neck, hands, feet, genitalia; lesion diameter 2.1 to 3.0 cm'), 
			('17274', 'Destruction, malignant lesion, any method, scalp, neck, hands, feet, genitalia; lesion diameter 3.1 to 4.0 cm'), 
			('17276', 'Destruction, malignant lesion, any method, scalp, neck, hands, feet, genitalia; lesion diameter over 4.0 cm'), 
			('17280', 'Destruction, malignant lesion, any method, face, ears, eyelids, nose, lips, mucous membrane; lesion diameter 0.5 cm or less'), 
			('17281', 'Destruction, malignant lesion, any method, face, ears, eyelids, nose, lips, mucous membrane; lesion diameter 0.6 to 1.0 cm'), 
			('17282', 'Destruction, malignant lesion, any method, face, ears, eyelids, nose, lips, mucous membrane; lesion diameter 1.1 to 2.0 cm'), 
			('17283', 'Destruction, malignant lesion, any method, face, ears, eyelids, nose, lips, mucous membrane; lesion diameter 2.1 to 3.0 cm'), 
			('17284', 'Destruction, malignant lesion, any method, face, ears, eyelids, nose, lips, mucous membrane; lesion diameter 3.1 to 4.0 cm'), 
			('17286', 'Destruction, malignant lesion, any method, face, ears, eyelids, nose, lips, mucous membrane; lesion diameter over 4.0 cm'), 
			('17304', 'Chemosurgery (Mohs micrographic technique), including removal of all gross tumor, surgical excision of tissue specimens, mapping, color coding of specimens, microscopic examination of specimens by the surgeon, and complete histopathologic preparation;  st'), 
			('19000', 'Puncture aspiration of cyst of breast;'), 
			('19020', 'Mastotomy w/ exploration or drainage of abscess, deep'), 
			('19100', 'Biopsy of breast; needle core'), 
			('19101', 'Biopsy of breast; incisional'), 
			('19110', 'Nipple exploration, w/ or w/o excision of a solitary lactiferous duct or a papilloma lactiferous duct'), 
			('19112', 'Excision of lactiferous duct fistula'), 
			('19120', 'Excision of cyst, fibroadenoma, or other benign or malignant tumor aberrant breast tissue, duct lesion or nipple lesion (except 19140), male or female, one or more lesions'), 
			('19125', 'Excision of breast lesion identified by preoperative placement of radiological marker; single lesion'), 
			('19140', 'Mastectomy for gynecomastia'), 
			('19160', 'Mastectomy, partial;'), 
			('19162', 'Mastectomy, partial; with axillary lymphadenectomy'), 
			('19180', 'Mastectomy, simple, complete'), 
			('19182', 'Mastectomy, subcutaneous'), 
			('19200', 'Mastectomy, radical, icnluding pectoral muscles, axillary lymph nodes'), 
			('19220', 'Mastectomy, radical, including pectoral muscles, axillary and internal mammary lymph nodes (Urban type operation)'), 
			('19240', 'Mastectomy, modified radical, including axillary lymph nodes, w/ or w/o pectoralis minor muscle, but excluding pectoralis major muscle'), 
			('19260', 'Excision of chest wall tumor including ribs'), 
			('19271', 'Excision of chest wall tumor involving ribs, w/ plastic reconstruction; w/o mediastinal lymphadenectomy'), 
			('19272', 'Excision of chest wall tumor involving ribs, w/ plastic reconstruction; w/ mediastinal lymphadenectomy'), 
			('19340', 'Immediate insertion of breast prosthesis following mastopexy, mastectomy or in reconstruction'), 
			('19342', 'Delayed insertion of breast prosthesis following mastopexy, mastectomy or in reconstruction'), 
			('19350', 'Nipple/areola reconstruction'), 
			('19357', 'Breast reconstruction, immediate or delayed, with tissue expander, including subsequent expansion'), 
			('19361', 'Breast reconstruction with latissimus dorsi flap, with or without prosthetic implant'), 
			('19364', 'Breast reconstruction with free flap'), 
			('19366', 'Breast reconstruction with other technique'), 
			('19367', 'Breast reconstruction with transverse rectus abdominis myocutaneous flap (TRAM), single pedicle, including closure of donor site;'), 
			('19369', 'Breast reconstruction with transverse rectus abdominis myocutaneous flap (TRAM), double pedicle, including closure of donor site'), 
			('19370', 'Open periprosthetic capsulotomy, breast'), 
			('19371', 'Periprosthetic capsulectomy, breast'), 
			('20200', 'Biopsy, muscle'), 
			('20206', 'Biopsy, muscle, percutaneous needle'), 
			('20220', 'Biopsy, bone, trocar, or needle; superficial (e.g., ilium, sternum, spinous process, ribs)'), 
			('20225', 'Biopsy, bone, trocar, or needle; deep (vertebral body, femur)'), 
			('20240', 'Biopsy, excisional; superficial (e.g., ilium, sternum, spinous process, ribs, trochanter of femur)'), 
			('20245', 'Biopsy, excisional; deep (e.g., humerus, ischium, femur)'), 
			('20250', 'Biopsy, vertebral body, open; thoracic'), 
			('20251', 'Biopsy, vertebral body, open; lumbar or cervical'), 
			('20520', 'Removal of foreign body in muscle or tendon sheath'), 
			('20600', 'Arthrocentesis, aspiration and/or injection; small joint, bursa or ganglion cyst (e.g., fingers, toes)'), 
			('20605', 'Arthrocentesis, aspiration and/or injection; intermediate joint, bursa or ganglion cyst (e.g., temporomandibular, acromioclavicular, wrist, elbow or ankle, olecranon bursa)'), 
			('20610', 'Arthrocentesis, aspiration and/or injection; major joint or bursa (e.g., shoulder, hip, knee joint, subacromial bursa)'), 
			('20615', 'Aspiration and injection for treatment of bone cyst'), 
			('20650', 'Insertion of wire or pin w/ application of skeletal traction, including removal'), 
			('20660', 'Application of cranial tongs, caliper, or stereotactic frame, including removal'), 
			('20661', 'Application of halo, including removal; cranial'), 
			('20662', 'Application of halo, including removal; pelvic'), 
			('20663', 'Application of halo, including removal; femoral'), 
			('20670', 'Removal of implant; superficial (e.g., buried wire, pin or rod)'), 
			('20680', 'Removal of implant; deep (e.g., buried wire, pin, screw, metal band, nail, rod or plate)'), 
			('20690', 'Application of a uniplane (pins or wires in one plane), unilateral, external fixation system'), 
			('20692', 'Application of multiplane (pins or wires in more than one plane), unilateral, external fixation system (e.g., llizarov, Monticelli type)'), 
			('20802', 'Replantation, arm (includes surgical neck of humerus through elbow joint), complete amputation'), 
			('20805', 'Replantation, forearm (includes radius and ulna to radial carpal joint), complete amputation'), 
			('20808', 'Replantation, hand (includes hand through metacarpophalangeal joint(s), complete amputation'), 
			('20816', 'Replantation, digit, excluding thumb (includes metacarpophalangeal joint to insertion of flexor sublimis tendon), complete amputation'), 
			('20822', 'Replantation, digit, excluding thumb (includes distal tip to sublimis tendon insertion), complete amputation'), 
			('20824', 'Replantation, thumb (includes carpometacarpal joint to MP joint), complete amputation'), 
			('20827', 'Replantation, thumb (includes distal tip to MP joint), complete amputation'), 
			('20838', 'Replantation, foot, complete amputation'), 
			('20900', 'Bone graft, any donor area; minor or small (e.g., dowel or button)'), 
			('20902', 'Bone graft, any donor area; major or large'), 
			('20910', 'Cartilage graft; costochondral'), 
			('20912', 'Cartilage graft; nasal septum'), 
			('20920', 'Fascia lata graft; by stripper'), 
			('20922', 'Fascia lata graft; by incision and area exposure, complex or sheet'), 
			('20924', 'Tendon graft, form a distance (e.g., palmaris, toe extensor, plantaris)'), 
			('20926', 'Tissue grafts, other (e.g., paratenon, fat, dermis)'), 
			('20930', 'Allograft for spine surgery only; morselized'), 
			('20931', 'Allograft for spine surgery only; structural'), 
			('20936', 'Autograft for spine surgery only (includes harvesting the graft); local (e.g., ribs, spinous process, or laminar fragments) obtained from same incision'), 
			('20937', 'Autograft for spine surgery only (includes harvesting the graft); morselized (thorugh separate skin or fascial incision)'), 
			('20938', 'Autograft for spine surgery only (includes harvesting the graft); structural, bicortical or tricortial (through separate skin or fascial incision)'), 
			('20955', 'Bone graft w/ microvascular anastomosis; fibula'), 
			('20956', 'Bone graft w/ microvascular anastomosis; iliac crest'), 
			('20957', 'Bone graft w/ microvascular anastomosis; metatarsal'), 
			('20962', 'Bone graft w/ microvascular anastomosis; other than fibula, iliac crest, or metatarsal'), 
			('20969', 'Free osteocutaneous flap w/ microvascular anastomosis; other than iliac crest, metatarsal, or great toe'), 
			('20970', 'Free osteocutaneous flap w/ microvascular anastomosis; iliac crest'), 
			('20972', 'Free osteocutaneous flap w/ microvascular anastomosis; metatarsal'), 
			('20973', 'Free osteocutaneous flap w/ microvascular anastomosis; great toe w/ web space'), 
			('20982', 'Ablation, bone tumor(s) (e.g., osteoid osteoma, metastasis) radiofrequency, percutaneous, including computed tomographic guidance'), 
			('21010', 'Arthrotomy, temporomandibular joint'), 
			('21015', 'Radical resection of tumor (e.g., malignant neoplasm), soft tissue of face or scalp'), 
			('21025', 'Excision of bone (e.g., for osteomyelitis or bone abscess); mandible'), 
			('21026', 'Excision of bone (e.g., for osteomyelitis or bone abscess); facial bone(s)'), 
			('21029', 'Removal by contouring of benign tumor of facial bone (e.g., fibrous dysplasia)'), 
			('21030', 'Excision of benign tumor or cyst of facial bone other than mandible'), 
			('21031', 'Excision of torus mandibularis'), 
			('21032', 'Excision of maxillary torus palatinus'), 
			('21034', 'Excision of malignant tumor of facial bone other than mandible'), 
			('21040', 'Excision of benign cyst or tumor of mandible; simple'), 
			('21041', 'Excision of benign cyst or tumor of mandible; complex'), 
			('21044', 'Excision of malignant tumor of mandible;'), 
			('21045', 'Excision of malignant tumor of mandible; radical resection'), 
			('21050', 'Condylectomy, temporomandibular joint'), 
			('21060', 'Meniscectomy, partial or complete, temporomandibular joint'), 
			('21070', 'Coronoidectomy'), 
			('21120', 'Genioplasty; augmentation (autograft, allograft, prosthetic material)'), 
			('21121', 'Genioplasty; sliding osteotomy, single piece'), 
			('21122', 'Genioplasty; sliding osteotomies, two or more osteotomies (e.g., wedge excision or bone wedge reversal for asymmetrical chin)'), 
			('21123', 'Genioplasty; sliding, augmentation w/ interpositional bone grafts (includes obtaining autografts)'), 
			('21125', 'Augmentation, mandibular body or angle; prosthetic material'), 
			('21127', 'Augmentation, mandibular body or angle; w/ bone graft, onlay or interpositional (includes obtaining autograft)'), 
			('21137', 'Reduction forehead; contouring only'), 
			('21138', 'Reduction forehead; contouring and application of prosthetic material or bone graft (includes obtaining autograft)'), 
			('21139', 'Reduction forehead; contouring and setback of anterior frontal sinus wall'), 
			('21141', 'Reconstruction midface, LeFort I; single piece, segment movement in any direction (e.g., for Long Face Syndrome), w/o bone graft'), 
			('21142', 'Reconstruction midface, LeFort I; two pieces, segment movement in any direction, w/o bone graft'), 
			('21143', 'Reconstruction midface, LeFort I; three or more pieces, segment movement in any direction, w/o bone graft'), 
			('21145', 'Reconstruction midface, LeFort I; single piece, segment movement in any direction, requiring bone grafts (includes obtaining autografts)'), 
			('21146', 'Reconstruction midface, LeFort I; two pieces, segment movement in any direction, requiring bone grafts (includes obtaining autografts) (e.g., ungrafted unilateral alveolar cleft)'), 
			('21147', 'Reconstruction midface, LeFort I; three or more pieces, segment movement in any direction, requiring bone grafts (includes obtaining autografts) (e.g., ungrafted bilateral alveolar cleft or multiple osteotomies)'), 
			('21150', 'Reconstruction midface, LeFort II; anterior intrusion (e.g., Treacher-Collins Syndrome)'), 
			('21151', 'Reconstruction midface, LeFort II; any direction, requiring bone grafts (includes obtaining autografts)'), 
			('21154', 'Reconstruction midface, LeFort III (extracranial), any type, requiring bone grafts (includes obtaining autografts); w/o LeFort I'), 
			('21155', 'Reconstruction midface, LeFort III (extracranial), any type, requiring bone grafts (includes obtaining autografts); w/ LeFort I'), 
			('21159', 'Reconstruction midface, LeFort III (extra and intracranial) w/ forehead advancement (e.g., mono bloc), requiring bone grafts (includes obtaining autografts); w/o LeFort I'), 
			('21160', 'Reconstruction midface, LeFort III (extra and intracranial) w/ forehead advancement (e.g., mono bloc), requiring bone grafts (includes obtaining autografts); w/ LeFort I'), 
			('21172', 'Reconstruction superior-lateral orbital rim and lower forehead, advancement or alteration, w/ or w/o grafts (includes obtaining autografts)'), 
			('21175', 'Reconstruction, bifrontal, superior-lateral orbital rims and lower forehead, advancement or alteration (e.g., plagiocephaly, trigonocephaly, brachycephaly), w/ or w/o grafts (includes obtaining autografts)'), 
			('21179', 'Reconstruction, entire or majority of forehead and/or supraorbital rims; w/ grafts (allograft or prosthetic material)'), 
			('21180', 'Reconstruction, entire or majority of forehead and/or supraorbital rims; w/ autograft (includes obtaining grafts)'), 
			('21181', 'Reconstruction by contouring of benign tumor of cranial bones (e.g., fibrous dysplasia), extracranial'), 
			('21182', 'Reconstruction of orbital walls, rims, forehead, nasoethmoid complex following intra-and extracranial excision of benign tumor of cranial bone (e.g., fibrous dysplasia), w/ multiple autografts (includes obtaining grafts); total area of bone grafting less'), 
			('21183', 'Reconstruction of orbital walls, rims, forehead, nasoethmoid complex following intra-and extracranial excision of benign tumor of cranial bone (e.g., fibrous dysplasia), w/ multiple autografts (includes obtaining grafts); total area of bone grafting great'), 
			('21184', 'Reconstruction of orbital walls, rims, forehead, nasoethmoid complex following intra-and extracranial excision of benign tumor of cranial bone (e.g., fibrous dysplasia), w/ multiple autografts (includes obtaining grafts); total area of bone grafting great'), 
			('21188', 'Reconstruction midface, osteotomies (other than LeFort type) and bone grafts (includes obtaining autografts)'), 
			('21193', 'Reconstruction of mandibular rami, horizontal, vertical, C, or L osteotomy; w/o bone graft'), 
			('21194', 'Reconstruction of mandibular rami, horizontal, vertical, C, or L osteotomy; w/ bone graft (includes obtaining graft)'), 
			('21195', 'Reconstruction of mandibular rami and/or body, sagittal split; w/o internal rigid fixation'), 
			('21196', 'Reconstruction of mandibular rami and/or body, sagittal split; w/ internal rigid fixation'), 
			('21198', 'Osteotomy, mandible, segmental'), 
			('21206', 'Osteotomy, maxilla, segmental (e.g., Wassmund or Schuchard)'), 
			('21210', 'Graft, bone; nasal, maxillary or malar areas (includes obtaining graft)'), 
			('21215', 'Graft, bone; mandible (includes obtaining graft)'), 
			('21230', 'Graft; rib cartilage, autogenous, to face, chin, nose or ear (includes obtaining graft)'), 
			('21235', 'Graft; ear cartilage, autogenous, to nose or ear (includes obtaining graft)'), 
			('21240', 'Arthroplasty, temporomandibular joint, w/ or w/o autograft (includes obtaining graft)'), 
			('21242', 'Arthroplasty, temporomandibular joint, w/ allograft'), 
			('21243', 'Arthroplasty, temporomandibular joint, w/ prosthetic joint replacement'), 
			('21244', 'Reconstruction of mandible, extraoral, w/ transosteal bone plate (e.g., mandibular staple bone plate)'), 
			('21245', 'Reconstruction of mandible or maxilla, subperiosteal implant; partial'), 
			('21246', 'Reconstruction of mandible or maxilla, subperiosteal implant; complete'), 
			('21247', 'Reconstruction of mandibular condyle w/ bone and cartilage autografts (includes obtaining grafts) (e.g., for hemifacial microsomia)'), 
			('21248', 'Reconstruction of mandible or maxilla, endosteal implant (e.g. blade, cylinder); partial'), 
			('21249', 'Reconstruction of mandible or maxilla, endosteal implant (e.g. blade, cylinder); complete'), 
			('21255', 'Reconstruction of zygomatic arch and glenoid fossa w/ bone and cartilage (includes obtaining autografts)'), 
			('21256', 'Reconstruction of orbit w/ osteotomies (extracranial) and w/ bone grafts (includes obtaining autografts) (e.g., micro-ophthalmia)'), 
			('21260', 'Periorbital osteotomies for orbital hypertelorism, w/ bone grafts'), 
			('21267', 'Orbital repositioning, periorbital osteotomies, unilateral, w/ bone grafts; extracranial approach'), 
			('21300', 'Closed treatment of skull fracture w/o operation'), 
			('21315', 'Closed treatment of nasal bone fracture'), 
			('21325', 'Open treatment of nasal fracture; uncomplicated'), 
			('21330', 'Open treatment of nasal fracture; complicated, w/ internal and/or external skeletal fixation'), 
			('21335', 'Open treatment of nasal fracture; w/ concomitant open treatment of fractured septum'), 
			('21336', 'Open treatment of nasal septal fracture, w/ or w/o stabilization'), 
			('21337', 'Closed treatment of nasal septal fracture'), 
			('21338', 'Open treatment of nasoethmoid fracture; w/o external fixation'), 
			('21339', 'Open treatment of nasoethmoid fracture; w/ external fixation'), 
			('21340', 'Percutaneous treatment of nasoethmoid complex fracture, w/ splint, wire or headcap fixation, including repair of canthal ligaments and/or the nasolacrimal apparatus'), 
			('21343', 'Open treatment of depressed frontal sinus fracture'), 
			('21344', 'Open treatment of complicated (e.g., comminuted or involving posterior wall) frontal sinus fracture, via coronal or multiple approaches'), 
			('21345', 'Closed treatment of nasomaxillary complex fracture (LeFort II type), w/ interdental wire fixation or fixation of denture or splint'), 
			('21346', 'Open treatment of nasomaxillary complex fracture (LeFort II type); w/ wiring and/or local fixation'), 
			('21347', 'Open treatment of nasomaxillary complex fracture (LeFort II type); requiring multiple open approaches'), 
			('21348', 'Open treatment of nasomaxillary complex fracture (LeFort II type); w/ bone grafting (includes obtaining graft)'), 
			('21355', 'Percutaneous treatment of fracture of malar area, including zygomatic arch and malar tripod, w/ manipulation'), 
			('21356', 'Open treatment of depressed zygomatic arch fracture (e.g., Gilles approach)'), 
			('21360', 'Open treatment of depressed malar fracture, including zygomatic arch and malar tripod'), 
			('21365', 'Open treatment of complicated (e.g., comminuted or involving cranial nerve foramina) fracture(s) of malar area, including zygomatic arch and malar tripod; w/ internal fixation and multiple surgical approaches'), 
			('21366', 'Open treatment of complicated (e.g., comminuted or involving cranial nerve foramina) fracture(s) of malar area, including zygomatic arch and malar tripod; w/ bone grafting (includes obtaining graft)'), 
			('21385', 'Open treatment of orbital floor blowout fracture; transantral approach (Caldwell-Luc type operation)'), 
			('21386', 'Open treatment of orbital floor blowout fracture; periorbital approach'), 
			('21387', 'Open treatment of orbital floor blowout fracture; combined approach'), 
			('21390', 'Open treatment of orbital floor blowout fracture; periorbital approach, w/ alloplastic or other implant'), 
			('21395', 'Open treatment of orbital floor blowout fracture; periorbital approach w/ bone graft (includes obtaining graft)'), 
			('21400', 'Closed treatment of fracture of orbit, except blowout'), 
			('21406', 'Open treatment of fracture of orbit, except blowout; w/o implant'), 
			('21407', 'Open treatment of fracture of orbit, except blowout; w/ implant'), 
			('21408', 'Open treatment of fracture of orbit, except blowout; w/ bone grafting (includes obtaining graft)'), 
			('21421', 'Closed treatment of palatal or maxillary fracture (LeFort I type), w/ interdental wire fixation or fixation of denture or splint'), 
			('21422', 'Open treatment of palatal or maxillary fracture (LeFort I type);'), 
			('21423', 'Open treatment of palatal or maxillary fracture (LeFort I type); complicated (comminuted or involving cranial nerve foramina), multiple approaches'), 
			('21431', 'Closed treatment of craniofacial separation (LeFort III type) using interdental wire fixation of denture or splint'), 
			('21432', 'Open treatment of craniofacial separation (LeFort III type); w/ wiring and/or internal fixation'), 
			('21433', 'Open treatment of craniofacial separation (LeFort III type); complicated (e.g., comminuted or involving cranial nerve foramina); multiple surgical approaches'), 
			('21435', 'Open treatment of craniofacial separation (LeFort III type); complicated, utilizing internal and/or external fixation techniques (e.g., head cap, halo device, and/or intermaxillary fixation)'), 
			('21436', 'Open treatment of craniofacial separation (LeFort III type); complicated, multiple surgical approaches, internal fixation, w/ bone grafting (includes obtaining graft)'), 
			('21440', 'Closed treatment of mandibular or maxillary alveolar ridge fracture'), 
			('21445', 'Open treatment of mandibular or maxillary alveolar ridge fracture'), 
			('21450', 'Closed treatment of mandibular fracture'), 
			('21452', 'Percutaneous treatment of mandibular fractue, w/ external fixation'), 
			('21453', 'Closed treatment of mandibular fracture; w/ interdental fixation'), 
			('21454', 'Open treatment of mandibular fracture; w/ external fixation'), 
			('21461', 'Open treatment of mandibular fracture; w/o interdental fixation'), 
			('21462', 'Open treatment of mandibular fracture; w/ interdental fixation'), 
			('21465', 'Open treatment of mandibular condylar fracture'), 
			('21470', 'Open treatment of complicated mandibular fracture by multiple surgical approaches including internal fixation, interdental fixation, and/or wiring of dentures or splints'), 
			('21480', 'Closed treatment of temporomandibular dislocation; initial or subsequent'), 
			('21485', 'Closed treatment of temporomandibular dislocation; complicated (e.g., recurrent requiring intermaxillary fixation or splinting), initial or subsequent'), 
			('21490', 'Open treatment of temporomandibular dislocation'), 
			('21493', 'Closed treatment of hyoid fracture'), 
			('21495', 'Open treatment of hyoid fracture'), 
			('21497', 'Interdental wiring, for condition other than fracture'), 
			('21501', 'Incision and drainage, deep abscess or hematoma, soft tissues of neck or thorax;'), 
			('21502', 'Incision and drainage, deep abscess or hematoma, soft tissues of neck or thorax; w/ partial rib ostectomy'), 
			('21510', 'Incision, deep, w/ opening of bone cortex (e.g., for osteomyelitis or bone abscess), thorax'), 
			('21550', 'Biopsy, soft tissue of neck or thorax'), 
			('21555', 'Excision tumor, soft tissue of neck or thorax; subcutaneous'), 
			('21556', 'Excision tumor, soft tissue of neck or thorax; deep, subfascial, intramuscular'), 
			('21557', 'Radical resection of tumor (e.g., malignant neoplasm), soft tissue of neck or thorax'), 
			('21600', 'Excision of rib, partial'), 
			('21610', 'Costotransversectomy'), 
			('21615', 'Excision  and/or cervical rib;'), 
			('21616', 'Excision  and/or cervical rib; w/ sympathectomy'), 
			('21620', 'Ostectomy of sternum, partial'), 
			('21627', 'Sternal debridement'), 
			('21630', 'Radical resection of sternum;'), 
			('21700', 'Division of scalenus anticus; w/o resection of cervical rib'), 
			('21705', 'Division of scalenus anticus; w/ resection of cervical rib'), 
			('21720', 'Division of sternocleidomastoid for torticollis, open operation'), 
			('21740', 'Reconstructive repair of pectus excavatum or carinatum'), 
			('21750', 'Closure of sternotomy separation w/ or w/o debridement'), 
			('21800', 'Closed treatment of rib fracture'), 
			('21805', 'Open treatment of rib fracture w/o fixation'), 
			('21810', 'Treatment of rib fracture requiring external fixation (flail chest)'), 
			('21820', 'Closed treatment of sternum fracture'), 
			('21825', 'Open treatment of sternum fracture w/ or w/o skeletal fixation'), 
			('21920', 'Biopsy, soft tissue of back or flank'), 
			('21930', 'Excision, tumor, soft tissue of back or flank'), 
			('21935', 'Radical resection of tumor (e.g., malignant neoplasm), soft tissue of back or flank'), 
			('22100', 'Partial excision of posterior vertebral component (e.g., spinous process, lamina or facet) for intrinsic bony lesion, single vertebral segment; cervical'), 
			('22101', 'Partial excision of posterior vertebral component (e.g., spinous process, lamina or facet) for intrinsic bony lesion, single vertebral segment; thoracic'), 
			('22102', 'Partial excision of posterior vertebral component (e.g., spinous process, lamina or facet) for intrinsic bony lesion, single vertebral segment; lumbar'), 
			('22110', 'Partial excision of vertebral body, for intrinsic bony lesion, w/o decompression of spinal cord or nerve root(s), single vertebral segment; cervical'), 
			('22112', 'Partial excision of vertebral body, for intrinsic bony lesion, w/o decompression of spinal cord or nerve root(s), single vertebral segment; thoracic'), 
			('22114', 'Partial excision of vertebral body, for intrinsic bony lesion, w/o decompression of spinal cord or nerve root(s), single vertebral segment; lumbar'), 
			('22210', 'Osteotomy of spine, posterior or posterolateral approach, one vertebral segment; cervical'), 
			('22212', 'Osteotomy of spine, posterior or posterolateral approach, one vertebral segment; thoracic'), 
			('22214', 'Osteotomy of spine, posterior or posterolateral approach, one vertebral segment; lumbar'), 
			('22220', 'Osteotomy of spine, including diskectomy, anterior approach, single vertebral segment; cervical'), 
			('22222', 'Osteotomy of spine, including diskectomy, anterior approach, single vertebral segment; thoracic'), 
			('22224', 'Osteotomy of spine, including diskectomy, anterior approach, single vertebral segment; lumbar'), 
			('22305', 'Closed treatment of vertebral process fracture(s)'), 
			('22310', 'Closed treatment of vertebral body fracture(s), requiring and including casting or bracing'), 
			('22325', 'Open treatment and/or reduction of vertebral fracture(s) and/or dislocation(s), posterior approach, one fractured vertebrae or dislocated segment; lumbar'), 
			('22326', 'Open treatment and/or reduction of vertebral fracture(s) and/or dislocation(s), posterior approach, one fractured vertebrae or dislocated segment; cervical'), 
			('22327', 'Open treatment and/or reduction of vertebral fracture(s) and/or dislocation(s), posterior approach, one fractured vertebrae or dislocated segment; thoracic'), 
			('22548', 'Arthrodesis, anterior transoral or extraoral technique, clivus-C1-C2 (atlas-axis), w/ or w/o excision of odontoid process'), 
			('22554', 'Arthrodesis, anterior interbody technique, including minimal diskectomy to prepare interspace (other than for decompression); cervical below C2'), 
			('22556', 'Arthrodesis, anterior interbody technique, including minimal diskectomy to prepare interspace (other than for decompression); thoracic'), 
			('22558', 'Arthrodesis, anterior interbody technique, including minimal diskectomy to prepare interspace (other than for decompression); lumbar'), 
			('22590', 'Arthrodesis; posterior technique, craniocervical (occiput-C2)'), 
			('22595', 'Arthrodesis, posterior technique, atlas-axis (C1-C2)'), 
			('22600', 'Arthrodesis, posterior or posterolateral technique, single level; cervical below C2 segment;'), 
			('22610', 'Arthrodesis, posterior or posterolateral technique, single level; cervical below C2 segment; thoracic (w/ or w/o lateral transverse technique)'), 
			('22612', 'Arthrodesis, posterior or posterolateral technique, single level; cervical below C2 segment; lumbar (w/ or w/o lateral transverse technique)'), 
			('22630', 'Arthrodesis, posterior interbody technique, single interspace; lumbar'), 
			('22800', 'Arthrodesis, posterior, for spinal deformity, w/ or w/o cast; up to 6 vertebral segments'), 
			('22802', 'Arthrodesis, posterior, for spinal deformity, w/ or w/o cast; 7 to 12 vertebral segments'), 
			('22804', 'Arthrodesis, posterior, for spinal deformity, w/ or w/o cast; 13 or more vertebral segments'), 
			('22808', 'Arthrodesis, anterior, for spinal deformity, w/ or w/o cast; 2 to 3 vertebral segments'), 
			('22810', 'Arthrodesis, anterior, for spinal deformity, w/ or w/o cast; 4 to 7 vertebral segments'), 
			('22812', 'Arthrodesis, anterior, for spinal deformity, w/ or w/o cast; 8 or more vertebral segments'), 
			('22840', 'Posterior non-segmental instrumentation (e.g., single Harrington rod technique)'), 
			('22841', 'Internal spinal fixation by wiring of spinous processes'), 
			('22842', 'Posterior segmental instrumentation (e.g., pedicle fixation, dual rods w/ multiple hooks and sublaminal wires); 3 to 6 vertebral segments'), 
			('22843', 'Posterior segmental instrumentation (e.g., pedicle fixation, dual rods w/ multiple hooks and sublaminal wires); 7 to 12 vertebral segments'), 
			('22844', 'Posterior segmental instrumentation (e.g., pedicle fixation, dual rods w/ multiple hooks and sublaminal wires); 13 or more vertebral segments'), 
			('22845', 'Anterior instrumentation; 2 to 3 vertebral segments'), 
			('22846', 'Anterior instrumentation; 4 to 7 vertebral segments'), 
			('22847', 'Anterior instrumentation; 8 or more vertebral segments'), 
			('22848', 'Pelvic fixation (attachment of caudal end of instrumentation to pelvic bony structures) other than sacrum'), 
			('22849', 'Reinsertion of spinal fixation device'), 
			('22850', 'Removal of posterior nonsegmental instrumentation (e.g., Harrington rod)'), 
			('22851', 'Application of prosthetic device (e.g., metal cages, methylmethacrylate) to vertebral defect or interspace'), 
			('22852', 'Removal of posterior segmental instrumentation'), 
			('22855', 'Removal of anterior instrumentation'), 
			('22900', 'Excision, abdominal wall tumor, subfascial (e.g., desmoid)')
		"); 
	
		Model::reguard();
    }
}
